"""
seed_context.py — the seeded corpus as MODEL CONTEXT rather than as somebody's
case list.

Per-user workspaces split the seeded data into two jobs that used to be one:

  * It is the demo workspace's CASE LIST. That half is workspace-scoped now —
    see auth.workspace_for_claims — so a new user's queue opens empty and
    stays theirs.
  * It is the calibration set the reasoning agent is grounded on. That half
    is deliberately NOT workspace-scoped, and this module is where it lives.

The distinction matters because the two halves fail in opposite directions. A
seeded case appearing in a stranger's queue is a data leak. A model that has
never been shown what "high severity" means in this domain, judging a real
user's first invoice, is a product that is worst for exactly the people it was
supposed to help most.

WHAT IS SHARED, AND WHAT IS NOT

Only the SHAPE of past outcomes crosses the workspace boundary: an exception
type, a rounded order of magnitude, and the risk level that was recorded for
it. Never an invoice number, never a vendor name, never an amount to the
rupee, and never a document. A calibration example is a statement about how
this product classifies severity — it is not evidence about anybody's ledger,
and it is never offered to the model as history it may reason from.

That boundary is enforced by construction below (`_exemplar` builds a new dict
from four whitelisted fields) rather than by a rule anybody has to remember.

WHY MAGNITUDE AND NOT THE AMOUNT

An exemplar exists to anchor "how big is big". Rounding 4,302.58 to "~1e3"
keeps everything the anchor needs and discards everything that could identify
a case. It also stops the model from pattern-matching a real figure back out
of the prompt.

WHY THIS IS NOT TRAINING

Nothing here fine-tunes anything. These are few-shot exemplars assembled at
call time and sent in the prompt, which means they are inspectable, versioned
with the seed file, and removable by deleting one line. "Trained on" would
mean a weight somewhere nobody can audit; this is the auditable version of
the same idea.

The financial guardrail is untouched by any of it: severity and language are
what the model is being calibrated on, and the money is still the
deterministic matcher's alone (services/exception_agent.py).
"""
from __future__ import annotations

import json
import math
import os
from collections import Counter
from functools import lru_cache
from typing import Optional

_SERVICES_DIR = os.path.dirname(os.path.abspath(__file__))
_BACKEND_DIR = os.path.dirname(_SERVICES_DIR)
_PORTFOLIO_PATH = os.path.join(_BACKEND_DIR, "data", "generated", "portfolio.json")

# How many exemplars go into a prompt. Small on purpose: the point is to anchor
# a scale, and a long list of past cases is a token bill that also invites the
# model to reason from other people's outcomes instead of this case's evidence.
MAX_EXEMPLARS = 8

# Only these four fields ever leave this module. Enforced in _exemplar.
EXEMPLAR_FIELDS = ("exception_type", "impact_magnitude", "risk_level", "match_score_band")


def _magnitude(amount: Optional[float]) -> str:
    """An order of magnitude, not an amount. '~1e5' anchors "six figures" for
    the model without carrying a single real number out of the corpus."""
    try:
        value = abs(float(amount or 0))
    except (TypeError, ValueError):
        return "0"
    if value < 1:
        return "0"
    return f"~1e{int(math.floor(math.log10(value)))}"


def _score_band(score) -> str:
    """Match scores bucketed, for the same reason amounts are rounded."""
    try:
        value = int(score)
    except (TypeError, ValueError):
        return "unknown"
    if value >= 95:
        return "95-100"
    if value >= 80:
        return "80-94"
    if value >= 60:
        return "60-79"
    return "below-60"


def _exemplar(case: dict) -> Optional[dict]:
    """One calibration example, built field by field from a whitelist.

    Constructed rather than filtered: a new dict with four keys cannot grow a
    vendor name because somebody added one to the seed file, which a
    blacklist-shaped comprehension over the case very much could.
    """
    exception_type = case.get("exception_type")
    risk_level = case.get("risk_level")
    if not exception_type or not risk_level:
        return None
    return {
        "exception_type": exception_type,
        "impact_magnitude": _magnitude(case.get("financial_impact")),
        "risk_level": risk_level,
        "match_score_band": _score_band(case.get("match_score")),
    }


@lru_cache(maxsize=1)
def _corpus() -> tuple[dict, ...]:
    """The labelled seeded outcomes, loaded once.

    An absent portfolio file is a normal state, not an error: it is gitignored
    and generated by scripts/generate_synthetic_data.py. Everything below
    degrades to "no calibration available", which the agent handles by simply
    not adding the section.
    """
    if not os.path.isfile(_PORTFOLIO_PATH):
        return ()
    try:
        with open(_PORTFOLIO_PATH, encoding="utf-8") as f:
            payload = json.load(f)
    except (OSError, ValueError):
        return ()
    out = []
    for case in payload.get("cases", []):
        exemplar = _exemplar(case)
        if exemplar:
            out.append(exemplar)
    return tuple(out)


@lru_cache(maxsize=1)
def severity_exemplars() -> tuple[dict, ...]:
    """A small, DETERMINISTIC, spread-out sample of the corpus.

    Spread matters more than size. 243 of the 320 seeded cases are clean, so
    the first eight rows of the file would teach the model that almost
    everything is low risk — which is true of the corpus and false of the
    queue, because a clean invoice never reaches the reasoning agent at all.
    So the sample takes the most frequent (exception_type, risk_level) pairs
    one at a time, and the clean ones not at all.

    Deterministic because a prompt that changes between two runs makes every
    difference in the output impossible to attribute.
    """
    corpus = [c for c in _corpus() if c["exception_type"] != "no_exception"]
    if not corpus:
        return ()

    grouped: dict[tuple[str, str], list[dict]] = {}
    for exemplar in corpus:
        grouped.setdefault(
            (exemplar["exception_type"], exemplar["risk_level"]), []).append(exemplar)

    # Most-represented pairs first; ties broken by name so the order is fixed.
    keys = sorted(grouped, key=lambda k: (-len(grouped[k]), k))
    return tuple(grouped[key][0] for key in keys[:MAX_EXEMPLARS])


@lru_cache(maxsize=1)
def corpus_stats() -> dict:
    """What the calibration set actually contains, for the settings endpoint.

    Published rather than kept internal: if the model is being grounded on
    something, the deployment should be able to see what and how much of it,
    and a reviewer asking "what is it calibrated on" deserves a real answer.
    """
    corpus = _corpus()
    exceptions = [c for c in corpus if c["exception_type"] != "no_exception"]
    return {
        "available": bool(corpus),
        "labelled_cases": len(corpus),
        "exception_cases": len(exceptions),
        "exemplars_in_prompt": len(severity_exemplars()),
        "exception_types": dict(
            sorted(Counter(c["exception_type"] for c in exceptions).items())),
        "fields_shared": list(EXEMPLAR_FIELDS),
        "source": os.path.relpath(_PORTFOLIO_PATH, _BACKEND_DIR).replace(os.sep, "/"),
    }


def calibration_block() -> Optional[dict]:
    """The prompt fragment, or None when there is nothing to calibrate on.

    None rather than an empty list, so the agent omits the section entirely
    instead of telling the model "here are zero examples", which reads as an
    instruction to be cautious and quietly shifts every severity it returns.
    """
    exemplars = severity_exemplars()
    if not exemplars:
        return None
    return {
        "note": (
            "Reference severity calibration from this product's labelled corpus. "
            "These are anonymised shapes — exception type, order of magnitude of "
            "impact, and the risk level recorded for it — not cases related to the "
            "one you are judging. Use them ONLY to keep your severity scale "
            "consistent with past classifications. Do not cite them, do not treat "
            "them as evidence about this vendor or this invoice, and do not let "
            "them change any number."
        ),
        "examples": [dict(e) for e in exemplars],
    }
