import { html, useState, useEffect } from "../../lib.js";
import { Badge } from "../ui/primitives.js";
import { SourceCitation } from "./SourceCitation.js";

export function DraftEditor({ draft, onOpenCitation }) {
  const [subject, setSubject] = useState(draft.subject);
  const [body, setBody] = useState(draft.body);

  useEffect(() => { setSubject(draft.subject); setBody(draft.body); }, [draft]);

  return html`
    <div class="stack gap-16">
      <div class="row gap-8" style=${{ flexWrap: "wrap" }}>
        <${Badge} tone="warning">Human review required<//>
        ${draft._ai_source === "ai"
          ? html`<${Badge} tone="accent">Generated by Gemini<//>`
          : null}
        <${Badge} tone="neutral">Owner: ${draft.recommended_owner}<//>
      </div>

      <div>
        <label class="field-label">Subject</label>
        <input class="input" value=${subject} onInput=${(e) => setSubject(e.target.value)} />
      </div>
      <div>
        <label class="field-label">Message</label>
        <textarea class="input" rows="9" value=${body} onInput=${(e) => setBody(e.target.value)} style=${{ resize: "vertical", fontFamily: "inherit" }}></textarea>
      </div>

      <div class="stack gap-8">
        <span class="field-label" style=${{ marginBottom: 0 }}>Source citations</span>
        <div class="row gap-8" style=${{ flexWrap: "wrap" }}>
          ${draft.citations.map((c, i) => html`<${SourceCitation} key=${i} citation=${c} onOpen=${onOpenCitation} />`)}
        </div>
      </div>

      <p class="text-muted text-small">
        This draft was generated by an AI agent from already-verified findings — it is never sent automatically.
        A human reviewer must approve it before it goes to ${draft.recommended_owner}.
      </p>
    </div>
  `;
}
