import { html } from "../../lib.js";
import { Drawer, Badge } from "../ui/primitives.js";

export function EvidenceDetailsDrawer({ node, onClose }) {
  if (!node) return null;
  return html`
    <${Drawer} open=${!!node} onClose=${onClose} title="Evidence detail">
      <div class="stack gap-16">
        <${Badge} tone=${node.type === "finding" ? "exception" : node.type === "document" ? "accent" : "neutral"}>
          ${node.type.replaceAll("_", " ")}
        <//>
        <h3 class="text-section-title">${node.label}</h3>
        ${node.detail ? html`<p class="text-secondary">${node.detail}</p>` : null}
        ${node.source_document_id ? html`
          <div class="panel-elevated stack gap-4" style=${{ padding: 14 }}>
            <span class="text-muted text-small">Source document</span>
            <span style=${{ fontWeight: 600 }}>${node.source_document_id}</span>
          </div>
        ` : null}
        <p class="text-muted text-small">
          This node is part of the evidence graph, assembled deterministically from the documents and
          tolerance rules on file — not generated by a language model.
        </p>
      </div>
    <//>
  `;
}
